module.exports = {
  state: {
    logotext: '@magic/types',
    title: '@magic/types',
    description: 'comprehensive and thoroughly tested type comparison library',
    menu: [
      { to: '/#install', text: 'install' },
      {
        to: '/#require',
        text: 'require',
        items: [
          { to: '/#require-single-function', text: 'import single function' },
          { to: '/#require-all-functions', text: 'import all functions' },
        ],
      },
      {
        to: '/#functions',
        text: 'functions',
        items: [
          { to: '-is', text: 'is' },
          { to: '-not', text: 'not' },
          { to: '-test', text: 'test' },
          { to: '-testtype', text: 'testType' },
          { to: '-type-compare', text: 'type comparisons' },
          { to: '-array', text: 'isArray' },
          { to: '-boolean', text: 'isBoolean' },
          { to: '-defined', text: 'isDefined' },
          { to: '-undefined', text: 'isUndefined' },
          { to: '-function', text: 'isFunction' },
          { to: '-number', text: 'isNumber' },
          { to: '-integer', text: 'isInteger' },
          { to: '-float', text: 'isFloat' },
          { to: '-object', text: 'isObject' },
          { to: '-string', text: 'isString' },
          { to: '-rgbaobject', text: 'isRGBAObject' },
          { to: '-rgbobject', text: 'isRGBObject' },
          { to: '-hexcolor', text: 'isHexColor' },
          { to: '-hexalphacolor', text: 'isHexAlphaColor' },
          { to: '-color', text: 'isColor' },
          { to: '-date', text: 'isDate' },
          { to: '-regexp', text: 'isRegExp' },
          { to: '-truthy', text: 'isTruthy' },
          { to: '-falsy', text: 'isFalsy' },
          { to: '-empty', text: 'isEmpty' },
          { to: '-error', text: 'isError' },
          { to: '-iterable', text: 'isIterable' },
          { to: '-email', text: 'isEmail' },
          { to: '-null', text: 'isNull' },
          { to: '-undefinedornull', text: 'isUndefinedOrNull' },
          { to: '-buffer', text: 'isBuffer' },
          { to: '-promise', text: 'isPromise' },
          { to: '-arguments', text: 'isArguments' },
          { to: '-uuid', text: 'isUUID' },
          { to: '-eq', text: 'isEq' },
          { to: '-not', text: 'isNot' },
          { to: '-deepequal', text: 'isDeepEqual' },
          { to: '-deepdifferent', text: 'isDeepDifferent' },
          { to: '-ismap', text: 'isMap' },
          { to: '-isset', text: 'isSet' },
          { to: '-isweakmap', text: 'isWeakMap' },
          { to: '-isweakset', text: 'isWeakSet' },
        ],
      },

      { to: '/#source', text: 'source' },
    ],
  },
}
